# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmaintenancecompanymodel',
            name='intervention_duration',
        ),
        migrations.RemoveField(
            model_name='externalmaintenancecompanymodel',
            name='intervention_time_days',
        ),
        migrations.RemoveField(
            model_name='externalmaintenancecompanymodel',
            name='intervention_time_hours',
        ),
        migrations.RemoveField(
            model_name='externalmaintenancecompanymodel',
            name='intervention_time_minutes',
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='entry_date',
            field=models.DateField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='entry_time',
            field=models.TimeField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='external_intervention_duration',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='external_intervention_time_days',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='external_intervention_time_hours',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='external_intervention_time_minutes',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='internal_intervention_duration',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='internal_intervention_time_days',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='internal_intervention_time_hours',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='internal_intervention_time_minutes',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='intervention_completion_date',
            field=models.DateField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='intervention_completion_time',
            field=models.TimeField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='intervention_start_date',
            field=models.DateField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='intervention_start_time',
            field=models.TimeField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='machine_down_time',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='machine_down_time_days',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='machine_down_time_hours',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='num_external_operators',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitysheetmodel',
            name='num_internal_operators',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
    ]
